/*
Note: In this problem you must NOT generate any output on your own.
Any such solution will be considered as being against the rules and its author will be disqualified.
The output of your solution must be generated by the uneditable code provided for you in the solution template.
An important concept in Object-Oriented Programming is the open/closed principle,
which means writing code that is open to extension but closed to modification.
In other words, new functionality should be added by writing an extension for the existing code rather than modifying
it and potentially breaking other code that uses it.
This challenge simulates a real-life problem where the open/closed principle can and should be applied.
A Tree class implementing a rooted tree is provided in the editor. It has the following publicly available methods:
getValue(): Returns the value stored in the node.
getColor(): Returns the color of the node.
getDepth(): Returns the depth of the node.
Recall that the depth of a node is the number of edges between the node and the tree's root,
so the tree's root has depth 0 and each descendant node's depth is equal to the depth of its parent node +1.
In this challenge, we treat the internal implementation of the tree as being closed to modification,
so we cannot directly modify it; however, as with real-world situations, the implementation is written in
such a way that it allows external classes to extend and build upon its functionality.
More specifically, it allows objects of the TreeVis class (a Visitor Design Pattern) to visit the tree and traverse
the tree structure via the accept method.
There are two parts to this challenge.
Part I: Implement Three Different Visitors
Each class has three methods you must write implementations for:
1. getResult(): Return an integer denoting the result, which is different for each class:
The SumInLeavesVisitor implementation must return the sum of the values in the tree's leaves only.
The ProductRedNodesVisitor implementation must return the product of values stored in all red nodes,
including leaves, computed modulo 10^9+7. Note that the product of zero values is equal to 1.
The FancyVisitor implementation must return the absolute difference between the sum of values stored in the tree's non-leaf
nodes at even depth and the sum of values stored in the tree's green leaf nodes. Recall that zero is an even number.
2. visitNode(TreeNode node): Implement the logic responsible for visiting the tree's non-leaf nodes such that the
getResult method returns the correct result for the implementing class' visitor.
3. visitLeaf(TreeLeaf leaf): Implement the logic responsible for visiting the tree's leaf nodes such that the
getResult method returns the correct result for the implementing class' visitor.
Part II: Read and Build the Tree
Read the n-node tree, where each node is numbered from 1 to n.
The tree is given as a list of node values (x[1],x[2],...,x[n]), a list of node colors (c[1],c[2],...,c[n]), and a list of edges.
Construct this tree as an instance of the Tree class. The tree is always rooted at node number 1.
Your implementations of the three visitor classes will be tested on the tree you built from the given input.
*Input Format
The first line contains a single integer, n, denoting the number of nodes in the tree.
The second line contains n space-separated integers describing the respective values of x[1],x[2],...,x[n].
The third line contains n space-separated binary integers describing the respective values of c[1],c[2],...,c[3].
Each c[i] denotes the color of the ith node, where 0 denotes red and 1 denotes green.
Each of the n-1 subsequent lines contains two space-separated integers, u[i] and v[i], describing an edge between nodes u[i] and v[i].
*Constraints
2<=n<=10^5
1<=x[i]<=10^3
c[i]∈{0,1}
1<=v[i],u[i]<=n
It is guaranteed that the tree is rooted at node 1.
*Output Format
Do not print anything to stdout, as this is handled by locked stub code in the editor.
The three getResult() methods provided for you must return an integer denoting the  for that class' visitor (defined above).
Note that the value returned by ProductRedNodesVisitor's getResult method must be computed modulo 10^9+7.
*Sample Input
5
4 7 2 5 12
0 1 0 0 1
1 2
1 3
3 4
3 5
*Sample Output
24
40
15
*Explanation
    4R
   /  \
 7G    2R
      /  \
    5R    12G
Locked stub code in the editor tests your three class implementations as follows:
Creates a SumInLeavesVisitor object whose getResult method returns the sum of the leaves in the tree, which is 7+5+12=24.
The locked stub code prints the returned value on a new line.
Creates a ProductOfRedNodesVisitor object whose getResult method returns the product of the red nodes, which is 4*2*5=40.
The locked stub code prints the returned value on a new line.
Creates a FancyVisitor object whose getResult method returns the absolute difference between the sum of the values of
non-leaf nodes at even depth and the sum of the values of green leaf nodes, which is |4-(7+12)| =15.
The locked stub code prints the returned value on a new line.
 */

package Advanced.Medium;

import java.util.ArrayList;
import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

import java.util.ArrayList;
import java.util.Scanner;





public class JavaVisitorPattern {
    enum Color {
        RED, GREEN
    }

    private static abstract class Tree {

        private int value;
        private Color color;
        private int depth;

        public Tree(int value, Color color, int depth) {
            this.value = value;
            this.color = color;
            this.depth = depth;
        }

        public int getValue() {
            return value;
        }

        public Color getColor() {
            return color;
        }

        public int getDepth() {
            return depth;
        }

        public abstract void accept(TreeVis visitor);
    }

    private static class TreeNode extends Tree {

        private ArrayList<Tree> children = new ArrayList<>();

        public TreeNode(int value, Color color, int depth) {
            super(value, color, depth);
        }

        public void accept(TreeVis visitor) {
            visitor.visitNode(this);

            for (Tree child : children) {
                child.accept(visitor);
            }
        }

        public void addChild(Tree child) {
            children.add(child);
        }
    }

    private static class TreeLeaf extends Tree {

        public TreeLeaf(int value, Color color, int depth) {
            super(value, color, depth);
        }

        public void accept(TreeVis visitor) {
            visitor.visitLeaf(this);
        }
    }

    private static abstract class TreeVis
    {
        public abstract int getResult();
        public abstract void visitNode(TreeNode node);
        public abstract void visitLeaf(TreeLeaf leaf);

    }

    private static class SumInLeavesVisitor extends TreeVis {

        int result = 0;

        public int getResult() {
            return result;
        }

        public void visitNode(TreeNode node) {
        }

        public void visitLeaf(TreeLeaf leaf) {
            result += leaf.getValue();
        }
    }

    private static class ProductOfRedNodesVisitor extends TreeVis {

        BigInteger result = BigInteger.ONE;

        public int getResult() {
            return result.mod(BigInteger.valueOf(((long)Math.pow(10,9)) + 7)).intValue();
        }

        public void visitNode(TreeNode node) {
            if(node.getColor() == Color.RED){
                result = result.multiply(BigInteger.valueOf(node.getValue()));
            }
        }

        public void visitLeaf(TreeLeaf leaf) {
            if(leaf.getColor() == Color.RED){
                result = result.multiply(BigInteger.valueOf(leaf.getValue()));
            }
        }
    }

    private static class FancyVisitor extends TreeVis {
        int result = 0;
        public int getResult() {
            return Math.abs(result);
        }

        public void visitNode(TreeNode node) {
            if(node.getDepth() % 2 == 0){
                result += node.getValue();
            }
        }

        public void visitLeaf(TreeLeaf leaf) {
            if(leaf.getColor() == Color.GREEN){
                result -= leaf.getValue();
            }
        }
    }

    private static class Node{
        public Color color;
        public int value;
        public ArrayList<Node> children;
        public Node(int value,Color color){
            this.value = value;
            this.color = color;
            children = new ArrayList<>();
        }
    }

    public static Tree solve() {
        Scanner scan = new Scanner(System.in);
        HashMap<Integer,Node> nodes = new HashMap<>();
        int n = scan.nextInt();
        int[] x = new int[n];
        int[] c = new int[n];
        for(int i = 0; i < n; i++){
            x[i] = scan.nextInt();
        }
        for(int i = 0; i < n; i++){
            c[i] = scan.nextInt();
        }
        for(int i = 0; i < n; i++){
            Node current = new Node(x[i],c[i] == 0 ? Color.RED : Color.GREEN);
            nodes.put(i+1,current);
        }
        for(int i = 0; i < n-1; i++){
            int one = scan.nextInt();
            int two = scan.nextInt();
            nodes.get(one).children.add(nodes.get(two));
            nodes.get(two).children.add(nodes.get(one));
        }
        Node rootNode = nodes.get(1);
        makeTree(null,rootNode);
        TreeNode root = new TreeNode(rootNode.value,rootNode.color,0);
        for(Node child : rootNode.children){
            addChild(root,child);
        }
        return root;
    }

    static void makeTree(Node parent, Node child){
        child.children.remove(parent);
        for(Node c : child.children){
            if(c != parent){
                makeTree(child,c);
            }
        }
    }

    static void addChild(TreeNode parent, Node child){
        if(child.children.size() == 0){
            TreeLeaf leaf = new TreeLeaf(child.value,child.color,parent.getDepth()+1);
            parent.addChild(leaf);
        }
        else{
            TreeNode node = new TreeNode(child.value,child.color,parent.getDepth()+1);
            parent.addChild(node);
            for(Node c : child.children){
                addChild(node,c);
            }
        }
    }

    public static void main(String[] args) {
        Tree root = solve();
        SumInLeavesVisitor vis1 = new SumInLeavesVisitor();
        ProductOfRedNodesVisitor vis2 = new ProductOfRedNodesVisitor();
        FancyVisitor vis3 = new FancyVisitor();

        root.accept(vis1);
        root.accept(vis2);
        root.accept(vis3);

        int res1 = vis1.getResult();
        int res2 = vis2.getResult();
        int res3 = vis3.getResult();

        System.out.println(res1);
        System.out.println(res2);
        System.out.println(res3);
    }
}
